/** Operational GlobeTrotter admin UI. It intentionally uses mock data and stays separate from traveler navigation. */
import { BarChart3, Bell, BookOpenCheck, Compass, LayoutDashboard, ListTree, MapPinned, Settings, ShieldCheck, Users, ArrowLeft, Search, Filter, MoreHorizontal } from "lucide-react";
import brandLogo from "@/assets/branding/globetrotter-logo.png";
import { useLocation } from "wouter";

const adminNav = [["/admin", "Overview", LayoutDashboard], ["/admin/users", "Users", Users], ["/admin/trips", "Trips", ListTree], ["/admin/cities", "Destinations", MapPinned], ["/admin/activities", "Activities", Compass], ["/admin/analytics", "Analytics", BarChart3]] as const;
const rows = {
  users: [["Mita Shah", "mita@example.com", "12 Aug 2026", "4 trips", "Traveler"], ["Aarav Mehta", "aarav@example.com", "10 Aug 2026", "2 trips", "Traveler"], ["Sara Khan", "sara@example.com", "08 Aug 2026", "7 trips", "Traveler"]],
  trips: [["Goa Adventure", "Mita Shah", "Mumbai → Goa", "Upcoming", "₹25,000"], ["Jaipur Notebook", "Aarav Mehta", "Jaipur → Udaipur", "Draft", "₹32,000"], ["Kerala Escape", "Sara Khan", "Kochi → Alleppey", "Upcoming", "₹28,000"]],
  cities: [["Goa", "India", "West Coast", "Balanced", "Active"], ["Jaipur", "India", "Rajasthan", "Balanced", "Active"], ["Udaipur", "India", "Rajasthan", "A little luxe", "Active"]],
  activities: [["Sunset Cruise", "Goa", "Nature", "₹1,200", "Active"], ["Fort Walk", "Goa", "Culture", "₹400", "Active"], ["Food Trail", "Jaipur", "Food", "₹950", "Review"]],
};

export function AdminConsolePage() {
  const [pathname, setLocation] = useLocation();
  const view = pathname.split("/").at(-1) || "admin";
  const isOverview = pathname === "/admin";
  const isAnalytics = view === "analytics";
  const tableKey = (view === "admin" || isAnalytics ? "trips" : view) as keyof typeof rows;
  return <div className="admin-console"><aside className="admin-sidebar"><div className="admin-brand"><img src={brandLogo} alt="GlobeTrotter" /><span>GlobeTrotter<small>ADMIN MODE</small></span></div><nav aria-label="Admin navigation">{adminNav.map(([path, label, Icon]) => <button key={path} className={pathname === path ? "active" : ""} onClick={() => setLocation(path)}><Icon size={18} />{label}</button>)}</nav><nav className="admin-system-nav"><span>System</span><button><Bell size={17} /> Notifications</button><button><Settings size={17} /> Settings</button><button><BookOpenCheck size={17} /> Audit Logs</button></nav><button className="admin-return" onClick={() => setLocation("/dashboard")}><ArrowLeft size={16} /> Traveler Dashboard</button></aside><main className="admin-main"><header className="admin-topbar"><div><span>GlobeTrotter / System administration</span><h1>{isOverview ? "Platform overview" : isAnalytics ? "Platform analytics" : `${view[0].toUpperCase()}${view.slice(1)} management`}</h1></div><button className="admin-profile"><Users size={16} /> Admin demo</button></header><div className="admin-atlas-trail"><span>System signal</span><i /><b>Atlas command center</b></div>{isOverview ? <AdminOverview onRoute={setLocation} /> : isAnalytics ? <AdminAnalytics /> : <AdminTable kind={tableKey} />}</main></div>;
}

function AdminOverview({ onRoute }: { onRoute: (path: string) => void }) { const metrics = [["Total users", "12,840", "+12.4%"], ["Trips created", "4,562", "+8.1%"], ["This month", "824", "+18.6%"], ["Published trips", "1,245", "+6.8%"]]; return <><section className="admin-kpis">{metrics.map(([label, value, delta]) => <article key={label}><span>{label}</span><strong>{value}</strong><small>{delta} vs. last month</small></article>)}</section><section className="admin-analysis-grid"><article className="admin-panel admin-line-panel"><div><span>Trip creation trend</span><h2>Planning is moving upward.</h2></div><div className="admin-line"><i /><i /><i /><i /><i /><i /><i /></div><p>Weekly travel-plan starts, based on realistic mock platform data.</p></article><article className="admin-panel"><div><span>Popular destinations</span><h2>Where travelers are heading</h2></div>{[["Goa", 84], ["Jaipur", 67], ["Kerala", 58], ["Udaipur", 42]].map(([city, value]) => <div className="admin-ranking" key={city as string}><span>{city}</span><i><b style={{ width: `${value}%` }} /></i><strong>{value}%</strong></div>)}</article></section><section className="admin-quick-grid"><button onClick={() => onRoute("/admin/users")}><Users size={21} /><span>Review traveler accounts</span></button><button onClick={() => onRoute("/admin/trips")}><ListTree size={21} /><span>Inspect active trips</span></button><button onClick={() => onRoute("/admin/analytics")}><BarChart3 size={21} /><span>Open platform analytics</span></button></section></>; }

function AdminAnalytics() { return <><section className="admin-kpis"><article><span>Average budget</span><strong>₹18,460</strong><small>Balanced travel is leading</small></article><article><span>Average trip length</span><strong>5.2 days</strong><small>+0.4 day vs. last month</small></article><article><span>Completion rate</span><strong>74%</strong><small>+5.1% route readiness</small></article><article><span>Returning users</span><strong>42%</strong><small>Healthy planning retention</small></article></section><section className="admin-analysis-grid"><article className="admin-panel admin-line-panel"><div><span>User and trip activity</span><h2>More atlases are being opened.</h2></div><div className="admin-line"><i /><i /><i /><i /><i /><i /><i /></div><p>Mock weekly growth trend, ready for a future analytics service.</p></article><article className="admin-panel"><div><span>Popular activity categories</span><h2>What goes into the plan</h2></div>{[["Nature", 78], ["Food", 64], ["Culture", 54], ["Adventure", 47]].map(([label, value]) => <div className="admin-ranking" key={label as string}><span>{label}</span><i><b style={{ width: `${value}%` }} /></i><strong>{value}%</strong></div>)}</article></section></>; }

function AdminTable({ kind }: { kind: keyof typeof rows }) { const labels: Record<keyof typeof rows, string[]> = { users: ["User", "Email", "Registered", "Trips", "Role"], trips: ["Trip", "Traveler", "Route", "Status", "Budget"], cities: ["Destination", "Country", "Region", "Cost", "Status"], activities: ["Activity", "Destination", "Category", "Cost", "Status"] }; return <><section className="admin-table-tools"><label><Search size={16} /><input placeholder={`Search ${kind}`} /></label><button><Filter size={16} /> Filters</button><button>Newest first</button></section><section className="admin-record-table" role="table"><div role="row" className="admin-record-head">{labels[kind].map((label) => <span key={label}>{label}</span>)}<span>Actions</span></div>{rows[kind].map((row) => <div role="row" key={row[0]}>{row.map((value) => <strong key={value}>{value}</strong>)}<button aria-label={`Manage ${row[0]}`}><MoreHorizontal size={18} /></button></div>)}</section><p className="admin-demo-note">These management records are realistic mock data for the frontend handoff. Future Odoo APIs should replace this data source without changing the layout contracts.</p></>; }
